-- Insert SQL Rules Here 
--==========================================================================================================================
-- Diplomacy_Responses
--==========================================================================================================================
INSERT INTO Diplomacy_Responses
(LeaderType, 				ResponseType, 										Response, 																Bias)
VALUES		('LEADER_RELIC_GAOZU', 	'RESPONSE_MINOR_CIV_COMPETITION', 			'TXT_KEY_LEADER_RELIC_GAOZU_MINOR_CIV_COMPETITION%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_RELIC_GAOZU_FIRSTGREETING%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_RELIC_GAOZU_DEFEATED%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_RELIC_GAOZU_REPEAT_TOO_MUCH%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_RELIC_GAOZU_REPEAT_TRADE_TOO_MUCH%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_RELIC_GAOZU_REPEAT_TOO_MUCH%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HELLO%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_POLITE_HELLO%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_AT_WAR%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HUMAN_AT_WAR%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_RELIC_GAOZU_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_RELIC_GAOZU_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 	2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_AGGRESSIVE_PLOT_BUYING%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 	2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_AGGRESSIVE_EXPANSION%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_FRIENDLY_STRONG_MILITARY%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_FRIENDLY_STRONG_ECONOMY%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 		2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_TOO_SOON_FOR_DOF', 							'TXT_KEY_LEADER_RELIC_GAOZU_TOO_SOON_FOR_DOF%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_RELIC_GAOZU_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_RELIC_GAOZU_DENOUNCE%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_RELIC_GAOZU_DENOUNCE%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_RELIC_GAOZU_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DOFED_FRIEND', 							'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOFED_FRIEND%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DOFED_ENEMY', 							'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOFED_ENEMY%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DENOUNCED_ENEMY', 						'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCED_ENEMY%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DENOUNCED_FRIEND', 						'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCED_FRIEND%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DOF_SO_AI_DOF', 						'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOF_SO_AI_DOF%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE', 				'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCE_SO_AI_DENOUNCE%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE', 					'TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOF_SO_AI_DENOUNCE%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_COOP_WAR_REQUEST', 							'TXT_KEY_LEADER_RELIC_GAOZU_COOP_WAR_REQUEST%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_COOP_WAR_TIME', 								'TXT_KEY_LEADER_RELIC_GAOZU_COOP_WAR_TIME%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_WORK_WITH_US', 								'TXT_KEY_LEADER_RELIC_GAOZU_DEC_FRIENDSHIP%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_PLOT_BUYING_WARNING', 						'TXT_KEY_LEADER_RELIC_GAOZU_PLOT_BUYING_WARNING%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 				'TXT_KEY_LEADER_RELIC_GAOZU_PLOT_BUYING_SERIOUS_WARNING%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 					'TXT_KEY_LEADER_RELIC_GAOZU_EXPANSION_SERIOUS_WARNING%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_EXPANSION_WARNING', 							'TXT_KEY_LEADER_RELIC_GAOZU_EXPANSION_WARNING%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 				'TXT_KEY_LEADER_RELIC_GAOZU_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_RETURNED_CIVILIAN', 							'TXT_KEY_LEADER_RELIC_GAOZU_RETURNED_CIVILIAN%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DECLARATION_PROTECT_CITY_STATE', 				'TXT_KEY_LEADER_RELIC_GAOZU_DECLARATION_PROTECT_CITY_STATE%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_BULLIED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_RELIC_GAOZU_BULLIED_PROTECTED_CITY_STATE%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_PROTECTED_CITY_STATEE%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DECLARATION_ABANDON_CITY_STATE', 				'TXT_KEY_LEADER_RELIC_GAOZU_DECLARATION_ABANDON_CITY_STATE%', 			2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_RELIC_GAOZU_DONT_SETTLE_YES%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_RELIC_GAOZU_DONT_SETTLE_NO%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_LUXURY_TRADE', 								'TXT_KEY_LEADER_RELIC_GAOZU_LUXURY_TRADE%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 						'TXT_KEY_LEADER_RELIC_GAOZU_OPEN_BORDERS_EXCHANGE%', 					2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_REQUEST', 									'TXT_KEY_LEADER_RELIC_GAOZU_RESPONSE_REQUEST%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_HOSTILE%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_HOSTILE%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_HOSTILE%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_EXCITED%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_EXCITED%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_EXCITED%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_SAD%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_BETRAYED%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_RELIC_GAOZU_DOW_GENERIC%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_RELIC_GAOZU_DOW_LAND%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_RELIC_GAOZU_DOW_WORLD_CONQUEST%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_RELIC_GAOZU_DOW_OPPORTUNITY%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_RELIC_GAOZU_DOW_DESPERATE%', 							2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_DOW_REGRET', 									'TXT_KEY_LEADER_RELIC_GAOZU_DOW_REGRET%', 								2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_RELIC_GAOZU_TOO_SOON_NO_PEACE%', 						2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',	'TXT_KEY_LEADER_RELIC_GAOZU_GOOD%', 									2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',				'TXT_KEY_LEADER_RELIC_GAOZU_GOOD%', 									2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',				'TXT_KEY_LEADER_RELIC_GAOZU_GOOD%', 									2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_WE_ATTACKED_MINOR_BAD',						'TXT_KEY_LEADER_RELIC_GAOZU_GOOD%', 									2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD', 	'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_ATTACKED_MINOR_BAD', 					'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD', 		'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD', 		'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD', 				'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 			'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD', 				'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_WE_ATTACKED_MINOR_GOOD', 						'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD', 					'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD', 		'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD', 		'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2),
('LEADER_RELIC_GAOZU', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD', 				'TXT_KEY_LEADER_RELIC_GAOZU_BAD%', 										2);
--==========================================================================================================================
--==========================================================================================================================
INSERT INTO Language_en_US
(Tag,																				Text)
VALUES		('TXT_KEY_LEADER_RELIC_GAOZU_FIRSTGREETING_1',							'Hail, traveler, to the Empire of Han. Please, do stay the night.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_FIRSTGREETING_2',							'Welcome to Han, friend. Do not cross us, and we will be stay loyal forever.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DEFEATED_1',								'Dynasties rise and fall. I suppose this was inevitable.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_REPEAT_TOO_MUCH_1',						'Again?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_REPEAT_TRADE_TOO_MUCH_1',					'Haven''t I alreay answered you?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HELLO_1',					'What do you want? Spit it out, quickly. My guards want to test their weapons.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_POLITE_HELLO_1',					'Oh, hello. I wasn''t expecting you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_AT_WAR_1',			'Your people are dying, and yet you continue to pursue war. Are you really this bloodthirsty.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HUMAN_AT_WAR_1',					'The people are Han support you in your war. Can I help you?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_AGGRESSIVE_MILITARY_WARNING_1',			'My people are threatened by your army''s presence. Please move it.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HOSTILE_AGGRESSIVE_MILITARY_WARNING_1',	'Don''t think you can move your army so close to my borders. My people will fight to the death for Han.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_AGGRESSIVE_PLOT_BUYING_1',		'Your aggressive claiming of new land worries me.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING_1','If you do not cease claiming land that is rightfully ours, then we will take it from you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_PLOT_BUYING_WARNING_1',					'That land is Han''s by right. Please refrain from taking any more.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_PLOT_BUYING_SERIOUS_WARNING_1',			'If you do not cease claiming land that is rightfully ours, then we will take it from you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_AGGRESSIVE_EXPANSION_1',			'Your people are intruding into Han territory. I trust that you''ll stop them?.'
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_AGGRESSIVE_EXPANSION_1',	'Your people hunger for land, ravaging the wilderness. Do they want to get away from you that badly?.')
			('TXT_KEY_LEADER_RELIC_GAOZU_EXPANSION_WARNING_1',						'Stop building new cities near our borders, or we''ll take them and burn them to the ground.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_EXPANSION_SERIOUS_WARNING_1',				'These cities of yours will make excellent test grounds for our new weapons.')
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_FRIENDLY_STRONG_MILITARY_1',		'Your military is so well organized and strong. Perhaps you''ll teach me how you manage it?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_FRIENDLY_STRONG_ECONOMY_1',		'I salute you for your wealth.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_FEW_CITIES_1',		'I see you''ve accepted that you can never measure up to the great Han dynasty. Good. Stay small, and I may yet spare you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_SMALL_ARMY_1',		'Was that your only warrior? Maybe I should send my spears and pikes to, ah, entertain him a little. Don''t worry, I''ll send you his head.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GREETING_HOSTILE_HUMAN_IS_WARMONGER_1',	'Fires burn across the land. Are you blind to the bitter screams of mothers? Does the blood running throught the streets not fill you with regret? You truly are a monster.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_TOO_SOON_FOR_DOF_1',						'Not yet. Perhaps later.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DENOUNCE_1',								'It pains me to do this, but for the good of my people and the good of the world, I must tell the others about you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DENOUNCE_2',								'You have forced my hand, and now the world will know.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_RESPONSE_TO_BEING_DENOUNCED_1',			'Do you really think this changes anything? No one will believe you.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOFED_FRIEND_1',						'The people of Han stand with you on your decision to befriend {1_CivName}.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOFED_ENEMY_1',						'{1_CivName}? You truly believe they can help you? How wrong you are.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCED_FRIEND_1',					'{1_CivName} is our friend, and we will defend them.')
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCED_ENEMY_1',					'Together, we will be able to deal with {1_CivName}, swiftly and adequately.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOF_SO_AI_DOF_1',					'What a coincedence! We have good relations with {1_CivName} as well. Together, we can defeat any evil.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DOF_SO_AI_DENOUNCE_1',				'I see you have aliied with {1_CivName}. No problem, that just makes it easier for me.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_HUMAN_DENOUNCE_SO_AI_DENOUNCE_1',			'I feel the same way about {1_CivName} as you do, friend.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_COOP_WAR_REQUEST_1',						'{1_Playername:textkey} must die. Will you join me, friend?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_COOP_WAR_TIME_1',							'You promised me that you would aid me against {1_PlayerName:textkey}. Will you keep your promise?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DEC_FRIENDSHIP_1',							'I extend my hand in friendship, and hope that you accept.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_RETURNED_CIVILIAN_1',						'I am eternally in your debt for rescuing my people.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_MINOR_CIV_COMPETITION_1',					'{1_MinorCivName:textkey} is in our sphere of influence. Do not attempt to intrude.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_MINOR_CIV_COMPETITION_2',					'Do not think you can so easily claim {1_MinorCivName:textkey} for yourself.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_PROTECTED_CITY_STATE_1',			'{@1_MinorCivName} is under our protection. Cease at once.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_BULLIED_PROTECTED_CITY_STATE_1',			'Are you mocking us? Believe me, we will defend {@1_MinorCivName} and turn back your assault.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DONT_SETTLE_NO_1',							'You do not dictate what we can do.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DONT_SETTLE_YES_1',						'I will not order my people to settle near you. If they do, it is not my concern.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_LUXURY_TRADE_1',							'Your luxuries are in demand in Han. Will you trade?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_OPEN_BORDERS_EXCHANGE_1',					'Only if we have open borders can our nations truly know each other.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_RESPONSE_REQUEST_1',						'It pains me to do so, but Han is desperate for help'),
			('TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_HOSTILE_1',						'Good. You have made the first move, and history will remember you for it.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_EXCITED_1',						'My men have wanted to test their weapons for a long time. In the history of Han, you will be but a footnote.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_SAD_1',							'I suppose this was inevitable. Yet I wonder, could we have done something to prevent this day?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_ATTACKED_BETRAYED_1',						'I should have known you would betray me.')
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_GENERIC_1',							'A storm descends upon you, and you die today.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_GENERIC_2',							'In the history of our country, you will be but a footnote.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_LAND_1',								'We will take back what is rightfully ours.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_WORLD_CONQUEST_1',						'You are but a stepping stone in my conquest of the world.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_OPPORTUNITY_1',						'Your nation is weak, gorged on excess. It is an opportunity I cannot resist.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_DESPERATE_1',							'I must do this. It is the only way.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_DOW_BETRAYAL_1',							'Did you not see this coming? Of course you didn''t. Now, you die.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_TOO_SOON_NO_PEACE_1',						'Are you kidding me?'),
			('TXT_KEY_LEADER_RELIC_GAOZU_BAD_1',									'No. Try harder.'),
			('TXT_KEY_LEADER_RELIC_GAOZU_GOOD_1',									'Why not?');