INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn) 
  VALUES ('RELIC_HAN_ATLAS', 256, 'HanIcon_256.dds', 4, 1),
         ('RELIC_HAN_ATLAS', 128, 'HanIcon_128.dds', 4, 1),
		 ('RELIC_HAN_ATLAS', 32,  'HanIcon_32.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 24,  'HanIcon_24.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 16,  'HanIcon_16.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 48,  'HanIcon_48.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 45,  'HanIcon_45.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 64,  'HanIcon_64.dds',  4, 1),
		 ('RELIC_HAN_ATLAS', 80,  'HanIcon_80.dds',  4, 1),
		 ('RELIC_HAN_JI_FLAG', 32, 'RelicHanJiFlag.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 128, 'AnishinaabeAlpha_128.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 16, 'AnishinaabeAlpha_16.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 24, 'AnishinaabeAlpha_24.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 32, 'AnishinaabeAlpha_32.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 45, 'AnishinaabeAlpha_45.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 48, 'AnishinaabeAlpha_48.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 64, 'AnishinaabeAlpha_64.dds', 1, 1),
		 ('RELIC_HAN_ALPHA', 80, 'AnishinaabeAlpha_80.dds', 1, 1);